version: '3.3'

services:
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      dockerfile: docker/backend/Dockerfile
      context: .
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
      - .:/usr/src/app/
    entrypoint: /usr/src/app/docker/backend/wsgi-entrypoint.sh
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  static:
  media:
  db:
  .:
